<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'_decimal_point' => '.',
	'_thousands_separator' => ',',
	'_thousands_suffix' => 'mil',
	'_millions_suffix' => 'M',
	'1_answer' => '1 resposta',
	'1_comment' => '1 comentário',
	'1_day' => '1 dia',
	'1_disliked' => '1 não gosto',
	'1_flag' => '1 denúncia',
	'1_hour' => '1 hora',
	'1_liked' => '1 gosto',
	'1_minute' => '1 minuto',
	'1_month' => '1 mês',
	'1_point' => '1 ponto',
	'1_question' => '1 pergunta',
	'1_second' => '1 segundo',
	'1_tag' => '1 tag',
	'1_user' => '1 usuário',
	'1_view' => '1 visualização',
	'1_vote' => '1 voto',
	'1_week' => '1 semana',
	'1_year' => '1 ano',
	'add_category_x_favorites' => 'Adicionar categoria ^ aos meus favoritos',
	'add_favorites' => 'Adicionar aos meus favoritos',
	'add_tag_x_favorites' => 'Adicionar tag ^ aos meus favoritos',
	'all_categories' => 'Todas as categorias',
	'anonymous' => 'anónimo',
	'answer_edited' => 'resposta editada',
	'answer_reshown' => 'resposta mostrada novamente',
	'answer_selected' => 'resposta selecionada',
	'answered' => 'respondeu',
	'answered_qs_in_x' => 'Perguntas mais respondidas em ^',
	'answered_qs_title' => 'Perguntas mais respondidas',
	'asked' => 'perguntou',
	'asked_related_q' => 'fez uma pergunta relacionada',
	'by_x' => 'por ^',
	'cancel_button' => 'Cancelar',
	'closed' => 'fechada',
	'comment_edited' => 'comentário editado',
	'comment_moved' => 'comentário movido',
	'comment_reshown' => 'comentário mostrado novamente',
	'commented' => 'comentou',
	'date_day_min_digits' => '1', // 1 or 2
	'date_format_other_years' => '^month ^day, ^year',
	'date_format_this_year' => '^month ^day',
	'date_month_1' => 'Jan',
	'date_month_2' => 'Fev',
	'date_month_3' => 'Mar',
	'date_month_4' => 'Abr',
	'date_month_5' => 'Maio',
	'date_month_6' => 'Jun',
	'date_month_7' => 'Jul',
	'date_month_8' => 'Ago',
	'date_month_9' => 'Set',
	'date_month_10' => 'Out',
	'date_month_11' => 'Nov',
	'date_month_12' => 'Dez',
	'date_year_digits' => '4', // 2 or 4
	'edited' => 'editou',
	'email_error' => 'Ocorreu um erro ao tentar enviar o e-mail.',
	'field_required' => 'Por favor insira algo neste campo',
	'file_upload_limit_exceeded' => 'O tamanho do ficheiro excede os limites do servidor',
	'general_error' => 'Ocorreu um erro no servidor - por favor tente novamente.',
	'hidden' => 'oculto',
	'highest_users' => 'Usuários com maior pontuação',
	'hot_qs_in_x' => 'Perguntas populares em ^',
	'hot_qs_title' => 'Perguntas populares',
	'image_not_read' => 'A imagem não pôde ser lida. Por favor carregue uma do tipo: ^',
	'image_too_big_x_pc' => 'Esta imagem é demasiado grande. Por favor redimensione para ^% e tente novamente.',
	'in_category_x' => 'em ^',
	'ip_address_x' => 'Endereço IP ^',
	'logged_in_x' => 'Olá ^',
	'max_length_x' => 'O comprimento máximo de caracteres é ^',
	'max_upload_size_x' => 'O tamanho máximo de upload é ^',
	'me' => 'eu',
	'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
	'min_length_x' => 'Por favor forneça mais informações - pelo menos ^ caracteres',
	'moved' => 'movido',
	'nav_activity' => 'Atividade',
	'nav_admin' => 'Admin',
	'nav_ask' => 'Fazer pergunta',
	'nav_categories' => 'Categorias',
	'nav_feedback' => 'Enviar feedback',
	'nav_home' => 'Início',
	'nav_hot' => 'Popular!',
	'nav_login' => 'Iniciar Sessão',
	'nav_logout' => 'Terminar Sessão',
	'nav_most_answers' => 'Mais respostas',
	'nav_most_recent' => 'Recente',
	'nav_most_views' => 'Mais visualizações',
	'nav_most_votes' => 'Mais votos',
	'nav_no_answer' => 'sem resposta',
	'nav_no_selected_answer' => 'Sem resposta selecionada',
	'nav_no_upvoted_answer' => 'Sem resposta votada',
	'nav_qa' => 'P&R',
	'nav_qs' => 'Perguntas',
	'nav_register' => 'Registar',
	'nav_tags' => 'Tags',
	'nav_unanswered' => 'Sem resposta',
	'nav_updates' => 'As minhas atualizações',
	'nav_users' => 'Usuários',
	'newest_users' => 'Usuários mais recentes',
	'no_active_users' => 'Nenhum usuário ativo encontrado',
	'no_answers_found' => 'Nenhuma resposta encontrada',
	'no_answers_in_x' => 'Nenhuma resposta em ^',
	'no_categories_found' => 'Nenhuma categoria encontrada',
	'no_category' => 'Nenhuma categoria',
	'no_comments_found' => 'Nenhum comentário encontrado',
	'no_comments_in_x' => 'Nenhum comentário em ^',
	'no_questions_found' => 'Nenhuma pergunta encontrada',
	'no_questions_in_x' => 'Nenhuma pergunta em ^',
	'no_related_qs_title' => 'Nenhuma pergunta relacionada encontrada',
	'no_results_for_x' => 'Nenhum resultado encontrado para ^',
	'no_tags_found' => 'Nenhuma tag encontrada',
	'no_una_questions_found' => 'Nenhuma pergunta sem resposta encontrada',
	'no_una_questions_in_x' => 'Nenhuma pergunta sem resposta em ^',
	'no_unselected_qs_found' => 'Nenhuma pergunta sem resposta selecionada encontrada',
	'no_unupvoteda_qs_found' => 'Nenhuma pergunta sem resposta votada encontrada',
	'page_label' => 'Página:',
	'page_next' => 'seguinte',
	'page_not_found' => 'Página não encontrada',
	'page_prev' => 'anterior',
	'popular_tags' => 'Tags mais populares',
	'questions_tagged_x' => 'Perguntas recentes marcadas ^',
	'recategorized' => 'recategorizado',
	'recent_activity_in_x' => 'Atividade recente em ^',
	'recent_activity_title' => 'Atividade recente neste site',
	'recent_as_in_x' => 'Perguntas respondidas recentemente em ^',
	'recent_as_title' => 'Perguntas respondidas recentemente',
	'recent_cs_in_x' => 'Perguntas comentadas recentemente em ^',
	'recent_cs_title' => 'Perguntas comentadas recentemente',
	'recent_qs_as_in_x' => 'Perguntas e respostas recentes em ^',
	'recent_qs_as_title' => 'Perguntas e respostas recentes',
	'recent_qs_in_x' => 'Perguntas recentes em ^',
	'recent_qs_title' => 'Perguntas recentes',
	'related_qs_title' => 'Perguntas relacionadas',
	'remove_favorites' => 'Remover dos meus favoritos',
	'remove_x_favorites' => 'Remover ^ dos meus favoritos',
	'reopened' => 'reaberta',
	'reshown' => 'mostrada novamente',
	'results_for_x' => 'Resultados da pesquisa para ^',
	'retagged' => 'remarcada',
	'save_button' => 'Guardar alterações',
	'search_button' => 'Pesquisar',
	'search_explanation' => 'Por favor introduza algum texto na caixa de pesquisa e tente novamente.',
	'search_title' => 'Resultados da pesquisa',
	'selected' => 'selecionada',
	'send_button' => 'Enviar',
	'since_x' => 'desde ^',
	'suggest_ask' => 'Ajude a começar ^1fazendo uma pergunta^2.',
	'suggest_category_qs' => 'Para ver mais, clique em todas as ^1perguntas desta categoria^2.',
	'suggest_qs' => 'Para ver mais, clique para ver a ^1lista completa de perguntas^2.',
	'suggest_qs_tags' => 'Para ver mais, clique para ver a ^1 lista completa de perguntas^2 ou ^3 tags populares^4.',
	'to_x' => 'para ^',
	'unanswered_qs_in_x' => 'Perguntas sem respostas em ^',
	'unanswered_qs_title' => 'Perguntas recentes sem respostas',
	'unselected_qs_in_x' => 'Perguntas sem resposta selecionada em ^',
	'unselected_qs_title' => 'Perguntas recentes sem uma resposta selecionada',
	'unupvoteda_qs_in_x' => 'Perguntas sem uma resposta votada em ^',
	'unupvoteda_qs_title' => 'Perguntas recentes sem uma resposta votada',
	'upload_limit' => 'Demasiados uploads - por favor tente novamente daqui a uma hora',
	'view_q_must_be_approved' => 'A sua conta deve primeiro ser aprovada para poder visualizar páginas de perguntas. Por favor aguarde ou ^1adicione mais informações^2.',
	'view_q_must_confirm' => 'Por favor ^5confirme o seu endereço eletrónico (e-mail)^6 para poder visualizar páginas de perguntas.',
	'view_q_must_login' => 'Por favor ^1inicie sessão^2 ou ^3registe-se^4 para poder visualizar páginas de perguntas.',
	'viewed_qs_in_x' => 'Perguntas mais visualizadas em ^',
	'viewed_qs_title' => 'Perguntas mais visualizadas',
	'vote_disabled_approve' => 'A sua conta deve primeiro ser aprovada antes de poder votar',
	'vote_disabled_down' => 'A permissão de votação negativa está apenas disponível para alguns usuários',
	'vote_disabled_down_approve' => 'A sua conta deve primeiro ser aprovada antes de poder votar negativamente',
	'vote_disabled_hidden_post' => 'Não pode votar em publicações ocultas',
	'vote_disabled_hidden_a' => 'Não pode votar em respostas ocultas',  // @deprecated
	'vote_disabled_hidden_q' => 'Não pode votar em perguntas ocultas',  // @deprecated
	'vote_disabled_level' => 'Votar é apenas disponível para alguns usuários',
	'vote_disabled_my_post' => 'Não pode votar nas suas próprias publicações',
	'vote_disabled_my_a' => 'Não pode votar nas suas próprias respostas',  // @deprecated
	'vote_disabled_my_q' => 'Não pode votar nas suas próprias perguntas',  // @deprecated
	'vote_disabled_q_page_only' => 'Por favor navegue para a página desta pergunta para votar',
	'vote_disabled_queued' => 'Só pode votar em publicações aprovadas',
	'vote_down_must_confirm' => 'Por favor ^5confirme o seu endereço de e-mail^6 para poder votar negativamente.',
	'vote_down_popup' => 'Clique para votar negativamente',
	'vote_limit' => 'Demasiados votos recebidos - por favor tenta novamente daqui a uma hora',
	'vote_must_confirm' => 'Por favor ^5confirme o seu endereço de e-mail^6 para poder votar.',
	'vote_must_login' => 'Por favor ^1inicie sessão^2 ou ^3registe-se^4 para votar.',
	'vote_not_allowed' => 'Não é permitido votar nisto',
	'vote_up_popup' => 'Clique para votar',
	'voted_down_popup' => 'Votou nisto negativamente - clique para remover o voto',
	'voted_qs_in_x' => 'Perguntas mais votadas em ^',
	'voted_qs_title' => 'Perguntas mais votadas',
	'voted_up_popup' => 'Votou nisto positivamente - clique para remover o voto',
	'written' => '', // blank in English - placeholder for other languages
	'x_ago' => '^ atrás',
	'x_answers' => '^ respostas',
	'x_comments' => '^ comentários',
	'x_days' => '^ dias',
	'x_disliked' => '^ não gosto',
	'x_flags' => '^ denúncias',
	'x_hours' => '^ horas',
	'x_liked' => '^ gosto',
	'x_minutes' => '^ minutos',
	'x_months' => '^ meses',
	'x_points' => '^ pontos',
	'x_questions' => '^ perguntas',
	'x_seconds' => '^ segundos',
	'x_tags' => '^ tags',
	'x_users' => '^ usuários',
	'x_views' => '^ visualizações',
	'x_votes' => '^ votos',
	'x_weeks' => '^ semanas',
	'x_years' => '^ anos',
);
