<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Miscellaneous language phrases


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'block_ip_button' => 'Bloquear endereço IP',
	'browse_categories' => 'Navegar pelas categorias',
	'captcha_approve_fix' => 'Esta verificação deixará de aparecer quando a sua conta for aprovada.',
	'captcha_confirm_fix' => 'Para evitar esta verificação no futuro, ^5confirme o seu endereço de e-mail^6.',
	'captcha_error' => 'Por favor complete a verificação anti-spam',
	'captcha_label' => 'Verificação anti-spam:',
	'captcha_login_fix' => 'Para evitar esta verificação no futuro, ^1inicie sessão^2 ou ^3registe-se^4.',
	'feed_a_edited_prefix' => 'Resposta editada: ',
	'feed_a_prefix' => 'Respondida: ',
	'feed_a_reshown_prefix' => 'Resposta mostrada novamente: ',
	'feed_a_selected_prefix' => 'Resposta selecionada: ',
	'feed_c_edited_prefix' => 'Comentário editado: ',
	'feed_c_moved_prefix' => 'Comentário movido: ',
	'feed_c_prefix' => 'Comentou: ',
	'feed_c_reshown_prefix' => 'Comentário mostrado novamente: ',
	'feed_closed_prefix' => 'Fechada: ',
	'feed_edited_prefix' => 'Editada: ',
	'feed_hidden_prefix' => 'Oculto: ',
	'feed_not_found' => 'Feed não encontrado',
	'feed_recategorized_prefix' => 'Recategorizado: ',
	'feed_reopened_prefix' => 'Reaberta: ',
	'feed_reshown_prefix' => 'Mostrada(o) novamente: ',
	'feed_retagged_prefix' => 'Remarcada: ',
	'feedback_email' => 'O seu e-mail: (opcional)',
	'feedback_empty' => 'Por favor preencha este campo para enviar comentários ou sugestões',
	'feedback_message' => 'Os seus comentários ou sugestões para ^:',
	'feedback_name' => 'O seu nome: (opcional)',
	'feedback_sent' => 'A sua mensagem abaixo foi enviada - obrigado.',
	'feedback_title' => 'Enviar feedback',
	'form_security_again' => 'Clique novamente para confirmar',
	'form_security_reload' => 'Por favor recarregue a página e tente novamente',
	'hide_all_ip_button' => 'Ocultar todas publicações deste IP',
	'host_name' => 'Nome do host:',
	'inbox' => 'Caixa de entrada',
	'matches_blocked_ips' => 'Corresponde a endereços IP bloqueados:',
	'message_empty' => 'Por favor introduza a sua mensagem a enviar a este usuário',
	'message_explanation' => 'Isto será enviado como uma notificação de ^. O seu endereço de e-mail não será revelado a menos que o inclua na sua mensagem.',
	'message_for_x' => 'A sua mensagem para ^:',
	'message_limit' => 'De momento não pode enviar mais mensagens privadas',
	'message_must_login' => 'Por favor ^1inicie sessão^2 ou ^3registe-se^4 para enviar mensagens privadas.',
	'message_recent_history' => 'Correspondência recente com ^',
	'message_sent' => 'A sua mensagem privada abaixo foi enviada',
	'more_favorite_qs' => 'Mais perguntas favoritas...',
	'more_favorite_tags' => 'Mais tags favoritas...',
	'more_favorite_users' => 'Mais usuários favoritos...',
	'my_favorites_title' => 'Os meus favoritos',
	'nav_all_my_updates' => 'Todas as minhas atualizações',
	'nav_my_content' => 'O meu conteúdo',
	'nav_my_details' => 'Editar perfil',
	'nav_my_favorites' => 'Os meus favoritos',
	'nav_user_activity' => 'Atividade',
	'nav_user_as' => 'Respostas',
	'nav_user_pms' => 'Mensagens',
	'nav_user_qs' => 'Perguntas',
	'nav_user_wall' => 'Mural',
	'next_step' => 'Próximo passo',
	'no_activity_from_x' => 'Nenhuma atividade de ^',
	'no_favorite_categories' => 'Nenhuma categoria favorita',
	'no_favorite_qs' => 'Nenhuma pergunta favorita',
	'no_favorite_tags' => 'Nenhuma tag favorita',
	'no_favorite_users' => 'Nenhum usuário favorito',
	'no_recent_updates' => 'Nenhuma atualização recente',
	'no_updates_content' => 'Nenhuma atualização recente para o meu conteúdo',
	'no_updates_favorites' => 'Sem atualização para os meus favoritos',
	'outbox' => 'Itens enviados',
	'pm_inbox_title' => 'Mensagens privadas recebidas',
	'pm_outbox_title' => 'Mensagens privadas enviadas',
	'private_message_title' => 'Enviar mensagem privada',
	'recent_activity_from_x' => 'Atividade recente de ^',
	'recent_updates_content' => 'Atualizações recentes para o meu conteúdo',
	'recent_updates_favorites' => 'Atualizações recentes para os meus favoritos',
	'recent_updates_title' => 'Atualizações recentes para mim',
	'site_in_maintenance' => 'Este site encontra-se atualmente em manutenção - por favor volte mais tarde.',
	'suggest_favorites_add' => 'Para adicionar uma pergunta ou outra publicação aos seus favoritos, clique em ^ no topo da página.',
	'suggest_update_favorites' => 'Para mais atualizações, adicione itens aos ^1seus favoritos^2.',
	'unblock_ip_button' => 'Desbloquear endereço IP',
	'your_a_commented' => 'resposta comentada',
	'your_a_edited' => 'resposta editada',
	'your_a_hidden' => 'resposta oculta',
	'your_a_questioned' => 'criou uma nova pergunta na sua resposta',
	'your_a_reshown' => 'resposta mostrada novamente',
	'your_a_selected' => 'resposta selecionada',
	'your_c_edited' => 'comentário editado',
	'your_c_followed' => 'comentário seguido',
	'your_c_hidden' => 'comentário ocultado',
	'your_c_moved' => 'comentário movido',
	'your_c_reshown' => 'comentário mostrado novamente',
	'your_q_answered' => 'pergunta respondida',
	'your_q_closed' => 'pergunta fechada',
	'your_q_commented' => 'pergunta comentada',
	'your_q_edited' => 'pergunta editada',
	'your_q_hidden' => 'pergunta oculta',
	'your_q_recategorized' => 'pergunta recategorizada',
	'your_q_reopened' => 'pergunta reaberta',
	'your_q_reshown' => 'pergunta mostrada novamente',
	'your_q_retagged' => 'pergunta denunciada',
);
