<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'1_answer_title' => '1 Resposta',
	'a_convert_to_c' => 'Converter esta resposta em um comentário',
	'a_convert_to_c_on' => 'Converter esta resposta em um comentário em:',
	'a_convert_warn' => 'Aviso: Esta conversão não pode ser revertida.',
	'a_convert_warn_cs' => 'Aviso: Esta conversão não pode ser revertida e também irá mover os comentários desta resposta.',
	'a_notify_email' => 'Enviar-me um e-mail para este endereço se a minha resposta for selecionada ou comentada:',
	'a_notify_label' => 'Enviar-me um e-mail se a minha resposta for selecionada ou comentada',
	'a_notify_x_label' => 'Enviar-me um e-mail (^) se a minha resposta for seleccionada ou comentada',
	'a_waiting_your_approval' => 'Esta resposta aguarda a sua aprovação',
	'a_your_waiting_approval' => 'A sua resposta será revisada e aprovada em breve.',
	'add_answer_button' => 'Adicionar resposta',
	'add_comment_button' => 'Adicionar comentário',
	'add_q_favorites' => 'Adicionar esta pergunta aos meus favoritos',
	'anon_name_label' => 'O seu nome para exibição (opcional):',
	'answer_button' => 'responder',
	'answer_limit' => 'Demasiadas respostas recebidas - por favor tente novamente daqui a uma hora',
	'answer_must_be_approved' => 'A sua conta deve primeiro ser aprovada antes de poder responder a uma pergunta. Por favor aguarde ou ^1adicione mais informações^2.',
	'answer_must_confirm' => 'Por favor ^5confirme o seu endereço de e-mail^6 para responder a esta pergunta.',
	'answer_must_login' => 'Por favor, ^1inicie sessão^2 ou ^3registe-se^4 para responder a esta pergunta.',
	'answer_q_popup' => 'Responder a esta pergunta',
	'approve_a_popup' => 'Aprovar esta resposta',
	'approve_button' => 'aprovar',
	'approve_c_popup' => 'Aprovar este comentário',
	'approve_q_popup' => 'Aprovar esta pergunta',
	'ask_button' => 'Faça a pergunta',
	'ask_follow_from_a' => 'A sua pergunta será relacionada a esta resposta:',
	'ask_follow_title' => 'Fazer pergunta relacionada',
	'ask_limit' => 'Demasiadas perguntas recebidas - por favor tente novamente dentro de uma hora',
	'ask_must_be_approved' => 'A sua conta deve primeiro ser aprovada antes de poder fazer uma pergunta. Por favor aguarde ou ^1adicione mais informações^2.',
	'ask_must_confirm' => 'Por favor ^5confirme o seu endereço de e-mail^6 para fazer uma pergunta.',
	'ask_must_login' => 'Por favor, ^1inicie sessão^2 ou ^3registe-se^4 para fazer uma pergunta.',
	'ask_same_q' => 'Antes de prosseguir, verifique se a sua pergunta não foi já feita:',
	'ask_title' => 'Faça uma pergunta',
	'c_notify_email' => 'Enviar-me um e-mail para este endereço se um comentário for adicionado após o meu:',
	'c_notify_label' => 'Enviar-me um e-mail se um comentário for adicionado após o meu',
	'c_notify_x_label' => 'Enviar-me um e-mail (^) se um comentário for adicionado após o meu',
	'c_waiting_your_approval' => 'Este comentário aguarda a sua aprovação',
	'c_your_waiting_approval' => 'O seu comentário será revisado e aprovado em breve.',
	'category_ask_not_allowed' => 'Não tem permissão para fazer perguntas nesta categoria',
	'category_js_note' => 'Para selecionar qualquer categoria, ative o Javascript no seu navegador.',
	'category_required' => 'Por favor escolha uma categoria',
	'claim_a_popup' => 'Atribuir esta resposta à minha conta de usuário',
	'claim_button' => 'Eu escrevi isto',
	'claim_c_popup' => 'Atribuir este comentário à minha conta de usuário',
	'claim_q_popup' => 'Atribuir esta pergunta à minha conta de usuário',
	'clear_flags_button' => 'Remover denúncias',
	'clear_flags_popup' => 'Remover todas as denúncias feitas por usuários',
	'close_button' => 'fechar',
	'close_duplicate' => 'Isto é uma duplicação de outra pergunta',
	'close_duplicate_error' => 'A pergunta duplicada não pôde ser encontrada - por favor tente introduzir o número de URL de uma pergunta diferente, por exemplo 123.',
	'close_form_button' => 'Fechar pergunta',
	'close_form_title' => 'Fechar esta pergunta',
	'close_original_note' => 'Também pode introduzir o número de URL da pergunta, por exemplo 123.',
	'close_original_title' => 'URL da pergunta original:',
	'close_q_popup' => 'Fechar esta pergunta para novas respostas',
	'close_reason_title' => 'Motivo do fecho desta pergunta, ou URL da pergunta duplicada:',
	'closed_as_duplicate' => 'fechada como duplicada de:',
	'closed_with_note' => 'fechada com a nota:',
	'comment_a_popup' => 'Adicionar um comentário a esta resposta',
	'comment_button' => 'comentar',
	'comment_limit' => 'Demasiados comentários recebidos - por favor tente novamente daqui a uma hora',
	'comment_must_be_approved' => 'A sua conta deve primeiro ser aprovada antes de poder adicionar um comentário. Por favor aguarde ou ^1adicione mais informações^2.',
	'comment_must_confirm' => 'Por favor ^5confirme o seu endereço de e-mail^6 para adicionar um comentário.',
	'comment_must_login' => 'Por favor, ^1inicie sessão^2 ou ^3registe-se^4 para adicionar um comentário.',
	'comment_on_a' => 'Na resposta: ',
	'comment_on_q' => 'Na pergunta: ',
	'comment_q_popup' => 'Adicionar um comentário a esta pergunta',
	'delete_a_popup' => 'Apagar esta resposta permanentemente',
	'delete_button' => 'eliminar',
	'delete_c_popup' => 'Apagar este comentário permanentemente',
	'delete_q_popup' => 'Apagar esta pergunta permanentemente',
	'duplicate_content' => 'O seu envio parece ser duplicado.',
	'edit_a_popup' => 'Editar esta resposta',
	'edit_a_title' => 'Editar resposta',
	'edit_button' => 'editar',
	'edit_c_popup' => 'Editar este comentário',
	'edit_c_title' => 'Editar comentário',
	'edit_must_confirm' => 'Please ^5confirm your email address^6 to edit this.',
	'edit_must_login' => 'Please ^1log in^2 or ^3register^4 to edit this.',
	'edit_q_popup' => 'Edit this question',
	'edit_q_title' => 'Edit Question',
	'example_tags' => 'Example tags: ',
	'flag_a_popup' => 'Denunciar esta resposta como spam, inapropriada ou fora de tópico',
	'flag_button' => 'denunciar',
	'flag_c_popup' => 'Denunciar este comentário como spam, inapropriado ou fora de tópico',
	'flag_hide_button' => 'denunciar e esconder',
	'flag_limit' => 'Demasiadas publicações denunciadas - por favor tente novamente daqui a uma hora',
	'flag_must_confirm' => 'Por favor ^5confirme o seu endereço de e-mail^6 para poder denunciar publicações.',
	'flag_must_login' => 'Por favor, ^1inicie sessão^2 ou ^3registe-se^4 para denunciar publicações.',
	'flag_not_allowed' => 'Não é permitido denunciar isto',
	'flag_q_popup' => 'Denunciar esta pergunta como spam, inapropriada ou fora de tópico',
	'follow_a_popup' => 'Fazer uma nova pergunta relacionada com esta resposta',
	'follow_button' => 'fazer pergunta relacionada',
	'follows_a' => 'relacionado com uma resposta para:',
	'follows_q' => 'sobre a pergunta:',
	'hide_a_popup' => 'Ocultar esta resposta',
	'hide_button' => 'ocultar',
	'hide_c_popup' => 'Ocultar este comentário',
	'hide_q_popup' => 'Ocultar esta pergunta',
	'matching_tags' => 'Tags correspondentes: ',
	'max_tags_x' => 'São permitidas no máximo ^ tags',
	'min_tags_x' => 'Por favor, forneça pelo menos ^ tag(s)',
	'notify_email_note' => 'Privacidade: O seu endereço de e-mail será apenas usado para enviar notificações.',
	'q_category_label' => 'Categoria:',
	'q_content_label' => 'Mais informações para a sua pergunta:',
	'q_hidden_author' => 'Esta pergunta foi oculta pelo seu autor',
	'q_hidden_flagged' => 'Esta pergunta foi denunciada e ocultada',
	'q_hidden_other' => 'Esta pergunta foi ocultada',
	'q_notify_email' => 'Envar-me um e-mail para este endereço se a minha pergunta for respondida ou comentada:',
	'q_notify_label' => 'Envar-me um e-mail se a minha pergunta for respondida ou comentada',
	'q_notify_x_label' => 'Envar-me um e-mail (^) se a minha pergunta for respondida ou comentada',
	'q_tags_comma_label' => 'Tags - usar vírgula (,) como separador:',
	'q_tags_label' => 'Tags - use hífens (-) para combinar palavras:',
	'q_title_label' => 'A sua pergunta em uma frase:',
	'q_waiting_approval' => 'Esta pergunta aguarda aprovação',
	'q_waiting_your_approval' => 'Esta pergunta aguarda a sua aprovação',
	'q_your_waiting_approval' => 'A sua pergunta será revisada e aprovada em breve.',
	'recat_button' => 'recategorizar',
	'recat_popup' => 'Alterar a categoria desta pergunta',
	'recat_q_title' => 'Recategorizar pergunta',
	'reject_a_popup' => 'Rejeitar esta resposta',
	'reject_button' => 'rejeitar',
	'reject_c_popup' => 'Rejeitar este comentário',
	'reject_q_popup' => 'Rejeitar esta pergunta',
	'remove_q_favorites' => 'Remover pergunta dos meus favoritos',
	'reopen_button' => 'reabrir',
	'reopen_q_popup' => 'Reabrir esta pergunta',
	'reply_button' => 'comentar',
	'reply_c_popup' => 'Responder a este comentário',
	'reshow_a_popup' => 'Mostrar novamente esta resposta',
	'reshow_button' => 'mostrar novamente',
	'reshow_c_popup' => 'Mostrar novamente este comentário',
	'reshow_q_popup' => 'Mostrar novamente esta pergunta',
	'retag_button' => 'mudar tag',
	'retag_cat_popup' => 'Alterar a categoria ou tags desta pergunta',
	'retag_popup' => 'Alterar tags desta pergunta',
	'retag_q_title' => 'mudar tags desta pergunta',
	'save_silent_label' => 'Guardar silenciosamente para não mostrar que isto foi editado',
	'select_popup' => 'Clique para selecionar como melhor resposta',
	'select_text' => 'Melhor resposta',
	'show_1_comment' => 'Mostrar 1 comentário',
	'show_1_previous_comment' => 'Mostrar 1 comentário anterior',
	'show_x_comments' => 'Mostrar ^ comentários',
	'show_x_previous_comments' => 'Mostrar ^ comentários anteriores',
	'unflag_button' => 'descartar denúncia',
	'unflag_popup' => 'Descartar a minha denúncia',
	'unselect_popup' => 'Clique para remover a seleção',
	'x_answers_title' => '^ Respostas',
	'your_answer_title' => 'A sua resposta',
	'your_comment_a' => 'O seu comentário nesta resposta:',
	'your_comment_q' => 'O seu comentário nesta pergunta:',
);
