<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for user management


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'about' => 'Sobre',
	'add_user_x_favorites' => 'Adicionar usuário ^ aos meus favoritos',
	'approve_required' => 'Por favor aguarda a aprovação da tua conta ou ^1adiciona mais informações^2.', // @deprecated
	'approve_title' => 'Aprovação de usuário pendente',
	'approve_user_button' => 'Aprovar usuário',
	'approved_user' => 'Usuário aprovado',
	'avatar_default' => 'Predefinido',
	'avatar_gravatar' => 'Mostrar o meu ^1Gravatar^2',
	'avatar_label' => 'Avatar:',
	'avatar_none' => 'Nenhum',
	'block_user_button' => 'Bloquear usuário',
	'blocked_users' => 'Usuários bloqueados',
	'category_level_add' => ' - ^1adicionar privilégios específicos de categoria^2',
	'category_level_in' => 'para a categoria abaixo:',
	'category_level_label' => 'Promovido para:',
	'category_level_none' => 'Nenhuma promoção',
	'change_email_link' => ' - ^1alterar e-mail^2',
	'change_password' => 'Alterar palavra-passe',
	'confirm_button' => 'Confirmar endereço de e-mail',
	'confirm_complete' => 'Obrigado - o teu endereço de e-mail foi confirmado.',
	'confirm_emailed' => 'Um link de confirmação foi enviado para o teu e-mail. Clica no link para confirmar o teu endereço de e-mail ou insire o código de confirmação no campo abaixo.',
	'confirm_required' => 'Para concluir o teu registo, clica no link de confirmação que te foi enviado por e-mail ou ^1pede um novo link^2.',
	'confirm_title' => 'Confirmação de endereço de e-mail',
	'confirm_wrong_log_in' => 'Código incorreto - por favor ^1inicia sessão^2 para enviar um novo link',
	'confirm_wrong_resend' => 'Código incorreto - clica no link abaixo para enviar um novo link',
	'delete_user_button' => 'Eliminar usuário',
	'edit_profile' => 'Editar Perfil',
	'edit_user_button' => 'Editar Usuário',
	'email_code_another' => 'envie outro',
	'email_code_emailed' => 'O teu código foi enviado pora o teu e-mail',
	'email_code_label' => 'Código:',
	'email_code_wrong' => 'Código incorreto',
	'email_confirmed' => 'Confirmado',
	'email_exists' => 'Este e-mail já pertence a uma conta diferente',
	'email_handle_label' => 'E-mail ou nome de usuário:',
	'email_invalid' => 'E-mail inválido - por favor verifica com atenção',
	'email_label' => 'E-mail:',
	'email_not_confirmed' => 'Ainda não confirmado',
	'email_please_confirm' => 'Por favor ^5confirme^6',
	'email_required' => 'Endereço de e-mail requerido - não é público',
	'forgot_link' => 'Esqueci-me da palavra-passe',
	'full_name' => 'Nome',
	'handle_blocked' => 'Este nome de usuário não é permitido - tenta um diferente',
	'handle_empty' => 'O nome de usuário não pode estar vazio',
	'handle_exists' => 'Este nome de usuário já se encontra em uso - tenta um diferente',
	'handle_has_bad' => 'O nome de usuário não pode conter: ^',
	'handle_label' => 'Nome de usuário:',
	'hide_all_user_button' => 'Ocultar todas as publicações deste usuário',
	'last_login_label' => 'Último início de sessáo:',
	'last_write_label' => 'Última ação escrita:',
	'level_admin' => 'Administrador',
	'level_editor' => 'Editor',
	'level_expert' => 'Especialista',
	'level_for_category' => '^1 para ^2',
	'level_in_general' => 'em geral',
	'level_moderator' => 'Moderador',
	'level_super' => 'Super Administrador',
	'location' => 'Localização',
	'log_in_to_access' => 'Agora podes ^1iniciar sessão^2 para aceder à tua conta.',
	'login_button' => 'Iniciar sessão',
	'login_limit' => 'Demasiadas tentativas de início de sessão - por favor tenta novamente daqui a uma hora',
	'login_title' => 'Iniciar sessão',
	'mass_mailings' => 'Envios de e-mails em massa (Newsletter):',
	'mass_mailings_explanation' => 'Subscrever à Newsletter',
	'member_for' => 'Membro há:',
	'member_type' => 'Tipo:',
	'new_password_1' => 'Nova palavra-passe:',
	'new_password_2' => 'Reintroduzir nova palavra-passe:',
	'no_blocked_users' => 'Nenhum usuário bloqueado encontrado',
	'no_permission' => 'Não tens permissão para executar esta operação',
	'old_password' => 'Palavra-passe antiga:',
	'only_shown_admins' => '(apenas mostrado para ti e administradores)',
	'only_shown_editors' => '(apenas mostrado para ti, editores e niveis acima)',
	'only_shown_experts' => '(apenas mostrado para ti, especialistas e niveis acima)',
	'only_shown_moderators' => '(apenas mostrado para ti, moderadores e administradores)',
	'password_changed' => 'Palavra-passe alterada com sucesso',
	'password_label' => 'Palavra-passe:',
	'password_min' => 'A palavra-passe deve ter pelo menos ^ caracteres',
	'password_mismatch' => 'As novas palavras-passe não coincidem',
	'password_none' => 'Nenhuma. Para iniciar sessão diretamente, define uma palavra-passe abaixo.',
	'password_sent' => 'A tua nova palavra-passe foi-te enviada por e-mail',
	'password_to_set' => 'Por favor, define na página da tua conta',
	'password_wrong' => 'Palavra-passe incorreta',
	'private_messages' => 'Mensagens privadas:',
	'private_messages_explanation' => 'Permitir que usuários te enviem mensagens privadas (sem ver o teu e-mail)',
	'profile_saved' => 'Perfil guardado',
	'register_button' => 'Registar',
	'register_limit' => 'Demasiados registos - por favor tenta novamente daqui a uma hora',
	'register_suspended' => 'O registo de novos usuários está temporariamente suspenso. Por favor tenta novamente em breve.',
	'register_title' => 'Regista-te como novo usuário',
	'registered_label' => 'Registrado:',
	'registered_user' => 'Usuário registado',
	'remember' => 'Lembrar-me',
	'remember_label' => 'Lembrar-me neste dispositivo',
	'remove_avatar' => 'Remover avatar:',
	'reset_title' => 'Redefinir palavra-passe esquecida',
	'save_profile' => 'Guardar Perfil',
	'save_user' => 'Guardar usuário',
	'send_confirm_button' => 'Enviar link de confirmação',
	'send_reset_button' => 'Enviar e-mail de redefinição de palavra-passe',
	'send_reset_note' => 'Uma mensagem será enviada para o teu endereço de e-mail com instruções.',
	'special_users' => 'Usuários especiais',
	'terms_not_accepted' => 'Deve marcar isto.',
	'unblock_user_button' => 'Desbloquear usuário',
	'unsubscribe' => 'Cancelar subscrição:',
	'unsubscribe_complete' => 'a tua subscrição foi cancelada da Newsletter por ^0. Podes voltar a subscrever-te a qualquer momento, nas tuas ^1definições de perfil^2.',
	'unsubscribe_title' => 'Cancelar subscrição',
	'unsubscribe_wrong_log_in' => 'Código incorreto - por favor ^1inicia sessão^2 para cancelar a subscrição',
	'user_blocked' => '(bloqueado)',
	'user_not_found' => 'Usuário não encontrado',
	'wall_posts' => 'Publicações de mural:',
	'wall_posts_explanation' => 'Permitir que usuários publiquem no teu mural (também receberás e-mails de notificação)',
	'website' => 'Site',
	'x_ago_from_y' => '^1 atrás via ^2',
);
